version: '2'
services:

  rabbitmq-processor:
      image: theweb/rabbitmq-processor-skybet:lastest
      environment:
        MONGODB_DB: "skybet"
        MONGODB_HOST: "192.168.1.234"
        MONGODB_PASS: "12345678C"
        MONGODB_PORT: "27017"
        MONGODB_USER: "user"
        RABBITMQ_DEFAULT_HOST: "192.168.1.234"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_PORT: "5672"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/feedme"
   
